name: Run Tasks on Spark

on:
  workflow_dispatch:
    inputs:
      taskName:
        description: Name of task directory
        required: true
        default: 'write_all_types'
      sparkVersions:
        description: JSON array of Spark versions to run on
        required: true
        default: '["2.0.0", "3.0.0"]'

jobs:
  make-parquet-files:
    name: Generate Parquet Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parquet-lot repo
        uses: actions/checkout@v2
      - name: Checkout polyspark repo
        uses: actions/checkout@v2
        with:
          repository: ursacomputing/polyspark
          path: polyspark
          token: ${{ secrets.PAT }}
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Run script
        shell: python
        run: |
          import json, os, sys
          os.mkdir('artifacts')
          sys.path.insert(1, os.environ['GITHUB_WORKSPACE'] + '/polyspark')
          sys.path.insert(1, os.environ['GITHUB_WORKSPACE'] + '/tasks/${{ github.event.inputs.taskName }}')
          import caller
          vers = json.loads('${{ github.event.inputs.sparkVersions }}')
          run(vers)
      #   continue-on-error: true
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Store files
        uses: actions/upload-artifact@v2
        with:
          name: parquet-lot
          path: artifacts
